### ISSUE TITLE
How to Implement this for iDempere ver 11 ? 

### ISSUE THREAD

**Issue by VianDriYanto** [JPiere/JPMS#1]
Hay Hideaki,

When i'm trying to install this on the my windows 11. I can not maven verify this Plugin. I Put the plugin outside the folder of iDempiere. Like this
iDProject
-- idempiere
-- jpms
when im trying to mvn verify inside folder jpms is not working, eventhough im already change the Manifest in org.adempiere.base and zk.

Regadrs
Avian

**Comment by JPiere** [comment]
This is not JPMS Issue.
Please see wiki : https://wiki.idempiere.org/en/JPiere_Development_environment_establishment

**Comment by VianDriYanto** [comment]
i already seen that, to using this plugin. I must put the source code JPMS inside the folder of idempiere? because on that link, i can not find information about it. Can i contact you using email?

**Comment by JPiere** [comment]
Written following at the bottom:

Additional setting for iDempiere6.1
From iDempiere6.1, We need to add <module> tag of JPiere plugin project to POM file for including installation package of iDempiere that is in base source cord folder.

**Comment by VianDriYanto** [comment]
any Screen Shoot for example can u provide?

**Comment by JPiere** [comment]
Translate below URL to your language. This URL is linked from wiki.
https://www.compiere-distribution-lab.net/jpiere-lab/dev/

**Comment by VianDriYanto** [comment]
Dear JPiere, Sorry to bother you again. Im successful to use your method
combine with feature-plugin. And now i'm adding to patch-ui.jar to
org.adempiere.ui for File ReportCtl and i'm creating another Module.
In Class ReportEngine, i'm adding something that will affect ReportCtl. The
problem is, something that i adding can not be read in ReportCtl. Error
like this
[image: image.png]
and this is may POM.xml for module patch-ui.jar
[image: image.png]
and this is my MANIFEST.MF
[image: image.png]

Because i'm stuck,
Thanks Before

Avian Driyanto

**Comment by JPiere** [comment]
This is not support forum.
You shouldn't post your questions here.
